import type { Product } from "@/lib/types"

export const electroProducts: Product[] = [
  {
    id: "heladora-yelmo-fh3300",
    name: "Heladora Yelmo FH-3300",
    description:
      "Creá deliciosos helados caseros, sorbetes y postres helados con ingredientes sanos y naturales con esta heladora Yelmo FH-3300. Ideal para toda la familia, cuenta con una capacidad de 1,5 litros y permite preparaciones rápidas en solo 20 a 40 minutos. Su diseño incluye una tapa transparente con abertura para agregar ingredientes mientras el motor trabaja, logrando una perfecta consistencia. Es totalmente automática con una sola tecla para operar el equipo y cuenta con soportes antideslizantes para mayor estabilidad.",
    price: 85000,
    discount: 0,
    category: "Electro",
    image: "/products/heladora-yelmo-1.webp",
    featured: true,
    specifications: {
      Marca: "Yelmo",
      Modelo: "FH-3300",
      Capacidad: "1,5 litros",
      "Tiempo de preparación": "20-40 minutos",
      Características:
        "Tapa transparente con abertura para ingredientes, Totalmente automática, Soportes antideslizantes",
      Operación: "Una sola tecla",
      Color: "Blanco con púrpura",
    },
    gallery: [
      "/products/heladora-yelmo-1.webp",
      "/products/heladora-yelmo-2.webp",
      "/products/heladora-yelmo-3.webp",
      "/products/heladora-yelmo-4.webp",
    ],
  },
  {
    id: "turbocirculador-indelplas-iv16",
    name: "Turbocirculador 16 Pulgadas Indelplas IV16 60W 3 en 1",
    description:
      "Turbo ventilador Indelplas de 16 pulgadas con diseño innovador y moderno. Cuenta con hélices balanceadas de alto rendimiento que lo hacen ultra silencioso y rejillas de alta seguridad en material resistente a los golpes. Su cabezal central se inclina verticalmente sobre un eje, permitiendo seleccionar la altura hacia dónde se desea ventilar. Es apto para piso y pared, tiene 3 velocidades, bajo consumo y diseño compacto, ideal para refrescar ambientes sin ruidos molestos. Acondicionado y diseñado para entornos industriales.",
    price: 45000,
    discount: 0,
    category: "Electro",
    image: "/products/turbo-indelplas-1.webp",
    featured: true,
    specifications: {
      Marca: "Indelplas",
      Modelo: "IV16",
      "Cantidad de aspas": "5",
      "Color de las aspas": "Negro",
      "Color de la estructura": "Negro",
      Diámetro: "40.64 cm (16 pulgadas)",
      Velocidades: "3",
      Potencia: "60W",
      Voltaje: "220V-50Hz",
      Características: "Silencioso, Apto para piso y pared, Bajo consumo, Regulable, Compacto",
      Origen: "Argentina",
    },
    gallery: [
      "/products/turbo-indelplas-1.webp",
      "/products/turbo-indelplas-2.webp",
      "/products/turbo-indelplas-3.webp",
    ],
  },
  {
    id: "radio-winco-w223",
    name: "Radio Winco W223 W223N portátil color negro",
    description:
      "Radio portátil de mano Winco W223N con sintonizador analógico AM/FM. Cuenta con antena telescópica para mejor recepción de señal y salida para auriculares. Su diseño compacto y ligero (solo 145g) la hace ideal para llevar a cualquier lugar. Funciona con 2 pilas AA, lo que garantiza su portabilidad sin depender de conexiones eléctricas.",
    price: 8500,
    discount: 0,
    category: "Electro",
    image: "/products/radio-winco.webp",
    featured: true,
    specifications: {
      Marca: "Winco",
      Modelo: "W223N",
      Bandas: "AM/FM",
      Antena: "Telescópica",
      Sintonizador: "Analógico",
      Alimentación: "2 pilas AA",
      Salida: "Para auriculares",
      Medidas: "13 x 7 x 3 cm",
      Peso: "145g",
      Color: "Negro",
    },
    gallery: ["/products/radio-winco.webp"],
  },
  {
    id: "calefon-epoxi",
    name: "CALEFON DE MATERIAL EPOXI CON TUVO DE NIVEL DE 20LTS DE CAPACIDAD",
    description:
      "Calefón de material epoxi con tubo de nivel y capacidad de 20 litros. Diseñado para proporcionar agua caliente de manera eficiente y segura. Su construcción en material epoxi garantiza durabilidad y resistencia a la corrosión, mientras que el tubo de nivel permite verificar fácilmente la cantidad de agua disponible. Ideal para hogares, cabañas o cualquier espacio que requiera un sistema confiable de calentamiento de agua.",
    price: 45000,
    discount: 0,
    category: "Electro",
    image: "/products/calefon-epoxi.jpeg",
    featured: true,
    specifications: {
      Material: "Epoxi",
      Capacidad: "20 litros",
      Características: "Con tubo de nivel",
      Marca: "Thim",
      Tipo: "Calefón de acumulación",
    },
    gallery: ["/products/calefon-epoxi.jpeg"],
  },
  {
    id: "pochoclera-winco-w321",
    name: "POCHOCLERA WINCO CARRITO W321",
    description:
      "Prepara deliciosas palomitas de maíz con esta pochoclera Winco con diseño vintage de carrito. Su sistema de cocción por aire caliente garantiza palomitas perfectas en cada uso. Con su atractivo diseño en color rojo, no solo es un electrodoméstico funcional sino también un elemento decorativo que añadirá un toque nostálgico a tu hogar.",
    price: 63000,
    discount: 0,
    category: "Electro",
    image: "/products/pochoclera-winco-2.webp",
    featured: true,
    specifications: {
      Marca: "Winco",
      Modelo: "W321",
      Color: "Rojo",
      Voltaje: "220V",
      Potencia: "1,2 kW",
      Diseño: "Vintage",
      "Sistema de cocción": "Aire caliente",
      Altura: "35 cm",
    },
    gallery: [
      "/products/pochoclera-winco-2.webp",
      "/products/pochoclera-winco-1.webp",
      "/products/pochoclera-winco-3.webp",
      "/products/pochoclera-winco-4.webp",
    ],
  },
  {
    id: "ventilador-winco-w1214",
    name: "WINCO VENTILADOR TURBO W1214",
    description:
      "Ventilador turbo Winco de 14 pulgadas con 5 aspas que proporciona un gran caudal de aire para mantener tus espacios frescos. Cuenta con un motor silencioso y ángulo ajustable que te permite dirigir el flujo de aire según tus necesidades. Su diseño compacto y eficiente lo convierte en el complemento perfecto para cualquier habitación durante los días calurosos.",
    price: 65000,
    discount: 0,
    category: "Electro",
    image: "/products/ventilador-winco.jpeg",
    featured: true,
    specifications: {
      Marca: "WINCO",
      Modelo: "W1214",
      Código: "VTU-W1214",
      Aspas: "5",
      Características: "Motor silencioso, Gran caudal de aire, Ángulo ajustable",
      Peso: "1.6 kg",
      Dimensiones: "40 cm alto x 40 cm ancho x 20 cm largo",
    },
    gallery: ["/products/ventilador-winco.jpeg"],
  },
  {
    id: "lavarropas-patrick",
    name: "LAVARROPAS SEMIAUTOMATICO LRPK56SB 5KG PATRICK",
    description:
      "Lavarropas semiautomático carga superior con capacidad de 5 Kg. Color Blanco. Cuenta con interruptor de seguridad, 6 programas y tambor de acero inoxidable. Voltaje: 220V/50HZ. Medidas(Al x An x Prof): 850 mm x 535 mm x 535 mm. Peso: 12 kg. Garantía 12 meses. Origen Argentina.",
    price: 249000,
    discount: 10,
    category: "Electro",
    image: "/products/lavarropas-patrick.jpeg",
    featured: true,
    specifications: {
      Capacidad: "5 Kg",
      Color: "Blanco",
      Programas: "6",
      Tambor: "Acero inoxidable",
      Voltaje: "220V/50HZ",
      Medidas: "850 mm x 535 mm x 535 mm",
      Peso: "12 kg",
      Garantía: "12 meses",
      Origen: "Argentina",
    },
    gallery: ["/products/lavarropas-patrick.jpeg"],
  },
]

