import type { Product } from "@/lib/types"

export const mueblesProducts: Product[] = [
  {
    id: "mueble-apoyo-cocina",
    name: "Mueble Apoyo Cocina Con Ruedas Frutero P/ Microondas",
    description:
      "Mueble multifuncional para cocina con ruedas, ideal para optimizar el espacio en tu hogar. Cuenta con un cajón superior para utensilios, tres bandejas extraíbles plásticas para frutas o verduras, y un compartimento con puerta y estante para almacenamiento adicional. Su superficie superior es perfecta para colocar un microondas u otros electrodomésticos. Las ruedas facilitan su movilidad, permitiéndote ubicarlo donde más lo necesites.",
    price: 85000,
    discount: 0,
    category: "Muebles",
    image: "/products/mueble-cocina-1.png",
    featured: true,
    specifications: {
      Funcionalidad: "Multifunción",
      Características: "Frutero (3 bandejas extraíbles plásticas), Porta microondas, 1 cajón, 1 puerta con estante",
      Movilidad: "Con ruedas",
      Ancho: "0,68 m",
      Alto: "0,91 m",
      Profundidad: "0,40 m",
      Material: "Melamina",
      Color: "Blanco",
    },
    gallery: ["/products/mueble-cocina-1.png", "/products/mueble-cocina-2.png", "/products/mueble-cocina-3.png"],
  },
  {
    id: "barra-desayuno-milano",
    name: "Barra Desayuno Milano 120X44X89 Cm Negro/Roble Dielfe",
    description:
      "La Barra Desayuno Milano de Dielfe es una opción elegante y funcional para su cocina o área de comedor. Con dimensiones de 120x44x89 cm, esta barra está diseñada para ofrecer un espacio cómodo y estilizado para disfrutar de desayunos, comidas rápidas o reuniones informales. El diseño en negro y roble combina la sofisticación del negro con la calidez del roble, creando un contraste atractivo y moderno que se adapta a diversos estilos decorativos. Su diseño compacto y vertical es ideal para espacios más reducidos, maximizando el uso del área disponible sin comprometer la funcionalidad.",
    price: 139000,
    discount: 0,
    category: "Muebles",
    image: "/products/barra-milano-1.jpeg",
    featured: true,
    specifications: {
      "Tipo de Producto": "Desayunadores",
      Color: "Marrón",
      Acabado: "Mate",
      Tono: "Natural-Negro",
      Alto: "89 Cm",
      Ancho: "44,5 Cm",
      Largo: "120 Cm",
      Peso: "12 Kg",
      Extensible: "No",
      Material: "Melamina",
      "Requiere Armado": "Si",
      "Más Información":
        "La barra desayunadora milano tiene un estilo moderno, con líneas simples, dentro de sus características destacamos sus patas metálicas con tubo de sección que no solo le aporta estética, sino que también resistencia, ideal para todo tipo de ambientes.",
      Origen: "Nacional",
      "País de Origen": "Argentina",
      Modelo: "MLD120",
    },
    gallery: ["/products/barra-milano-1.jpeg", "/products/barra-milano-2.jpeg", "/products/barra-milano-3.jpeg"],
  },
  {
    id: "mesa-luz-nordica",
    name: "Mesa De Luz Nórdica Escandinava",
    description:
      "Mesa de luz con diseño nórdico/escandinavo que combina funcionalidad y estética minimalista. Cuenta con un cajón superior y un compartimento inferior con puerta rebatible que proporcionan amplio espacio de almacenamiento para tus objetos personales. Fabricada en madera de pino natural sin tratamiento, esta pieza aporta calidez y un toque contemporáneo a cualquier dormitorio. Sus patas inclinadas le dan un aspecto moderno y distintivo, ideal para espacios con estilo escandinavo.",
    price: 50000,
    discount: 0,
    category: "Muebles",
    image: "/products/mesa-luz-escandinava-1.webp",
    featured: true,
    specifications: {
      Material: "Madera natural",
      Acabado: "Sin lustre",
      Almacenamiento: "1 cajón + puerta rebatible",
      Alto: "60 cm",
      Ancho: "40 cm",
      Profundidad: "30 cm",
      Estilo: "Nórdico/Escandinavo",
    },
    gallery: [
      "/products/mesa-luz-escandinava-1.webp",
      "/products/mesa-luz-escandinava-2.webp",
      "/products/mesa-luz-escandinava-3.webp",
    ],
  },
  {
    id: "modulo-escandinavo",
    name: "Módulo Escandinavo LE075",
    description:
      "El módulo de dos cuerpos de la línea Escandinava, se caracteriza por su estilo minimalista. El diseño está compuesto por un cuerpo principal de melanina y patas de PVC. Este mueble posee seis divisiones internas, dos cerradas con puertas y cuatro libres. Con terminaciones en color blanco combinado con roble bardolino y tiradores de color plateado los cuales acompañan con la estética discreta del diseño. Este módulo se puede adaptar perfectamente al ambiente en el que se lo utilice.",
    price: 99000,
    discount: 0,
    category: "Muebles",
    image: "/products/modulo-escandinavo.png",
    featured: true,
    specifications: {
      "Material del Producto": "Melamina",
      "Cantidad de puertas": "2",
      "Cantidad de estantes": "6",
      "Cantidad de cajones": "0",
      Manijas: "2",
      Medidas: "132*75*30",
      "Requiere armado": "Sí",
      Color: "Blanco con roble",
    },
    gallery: [
      "/products/modulo-escandinavo.png",
      "/products/modulo-escandinavo-2.png",
      "/products/modulo-escandinavo-3.png",
    ],
  },
  {
    id: "silla-escandinava",
    name: "SILLA ESCANDINAVA BOLONIA CAÑO BLANCO TAPIZADO GRIS",
    description:
      "La silla Bolonia combina estilo y confort en un diseño escandinavo elegante y funcional. Su estructura de caño blanco aporta resistencia y estabilidad, mientras que su asiento tapizado en gris brinda comodidad y sofisticación. El respaldo de madera añade un toque cálido y natural, ideal para integrarse en diferentes espacios.",
    price: 55000,
    discount: 0,
    category: "Muebles",
    image: "/products/silla-escandinava.png",
    featured: true,
    specifications: {
      Diseño: "Escandinavo",
      Estructura: "Caño blanco",
      Asiento: "Tapizado en gris",
      Respaldo: "Madera",
      Alto: "84,5 cm",
      Ancho: "43,5 cm",
      Profundidad: "46 cm",
    },
    gallery: ["/products/silla-escandinava.png", "/products/silla-escandinava-2.png"],
  },
  {
    id: "silla-escandinava-negra",
    name: "SILLA ESCANDINAVA BOLONIA CAÑO NEGRO TAPIZADO PLOMO",
    description:
      "La silla Bolonia combina estilo y confort en un diseño escandinavo elegante y funcional. Su estructura de caño negro aporta resistencia y estabilidad, mientras que su asiento tapizado en gris plomo brinda comodidad y sofisticación. El respaldo de madera añade un toque cálido y natural, ideal para integrarse en diferentes espacios.",
    price: 55000,
    discount: 0,
    category: "Muebles",
    image: "/products/silla-bolonia-negra-1.png",
    featured: false,
    specifications: {
      Diseño: "Escandinavo, moderno y versátil",
      Estructura: "Caño negro, resistente y duradera",
      Asiento: "Tapizado en gris plomo, cómodo y fácil de combinar",
      Respaldo: "Madera, aportando un toque natural",
      "Uso recomendado": "Comedores, livings, oficinas o espacios de reunión",
      Alto: "84,5 cm",
      Ancho: "43,5 cm",
      Profundidad: "46 cm",
    },
    gallery: ["/products/silla-bolonia-negra-1.png", "/products/silla-bolonia-negra-2.png"],
  },
  {
    id: "mesa-puket",
    name: "Mesa Puket Auxiliar",
    description:
      "Mesa de diseño redondeado modelo Puket, pensada para ser utilizada al exterior, fabricada con material resistente y duradero. Disponible en color blanco y gris. Todos nuestros productos plásticos son fáciles de limpiar, resistentes a los rayos UV y están elaborados para que no dañen el ambiente.",
    price: 17000,
    discount: 0,
    category: "Muebles",
    image: "/products/mesa-puket-blanca.jpeg",
    featured: false,
    specifications: {
      Material: "Plástico resistente",
      Uso: "Interior y exterior",
      "Resistente a rayos UV": "Sí",
      "Fácil limpieza": "Sí",
      "Colores disponibles": "Blanco, Gris",
      Diseño: "Redondeado",
    },
    gallery: ["/products/mesa-puket-blanca.jpeg", "/products/mesa-puket-gris.webp"],
  },
  {
    id: "mesa-luz-1-puerta-1-cajon",
    name: "Mesa de Luz 1 Puerta 1 Cajón",
    description:
      "Mesa de luz funcional y moderna con un cajón y una puerta, ideal para el dormitorio. Fabricada en MDP de 15 mm impreso con revestimiento acrílico UV que garantiza durabilidad y resistencia. Disponible en colores blanco y chocolate, se adapta perfectamente a cualquier estilo de decoración. Sus medidas compactas (56 cm de alto, 38 cm de ancho y 37 cm de profundidad) la hacen perfecta para espacios reducidos.",
    price: 41175,
    discount: 15,
    category: "Muebles",
    image: "/products/mesa-luz-chocolate.jpeg",
    featured: true,
    specifications: {
      "Material principal": "MDP 15 mm impreso",
      Fondo: "MDF 3 mm",
      Revestimiento: "Acrílico UV",
      Cajones: "1",
      Manijas: "Plástico (Gris Plata)",
      "Correderas de cajones": "Plásticas",
      "Carga admisible total": "15 kg",
      Alto: "0,56 m",
      Ancho: "0,38 m",
      Profundidad: "0,37 m",
      "Colores disponibles": "Blanco, Chocolate",
    },
    gallery: [
      "/products/mesa-luz-chocolate.jpeg",
      "/products/mesa-luz-blanca.jpeg",
      "/products/mesa-luz-chocolate-abierta.jpeg",
      "/products/mesa-luz-blanca-abierta.jpeg",
      "/products/mesa-luz-blanca-ambiente.jpeg",
    ],
  },
  {
    id: "placard-2-puertas-2-cajones",
    name: "Placard 2 Puertas 2 Cajones",
    description:
      "Placard funcional y espacioso con dos puertas y dos cajones, perfecto para organizar tu ropa y accesorios. Fabricado en melamina de 15 mm que garantiza durabilidad y resistencia. Disponible en colores caoba, chocolate y blanco para adaptarse a cualquier estilo de decoración. Sus dimensiones (1,81 m de alto, 0,57 m de ancho y 0,46 m de profundidad) ofrecen amplio espacio de almacenamiento sin ocupar demasiado espacio en la habitación.",
    price: 77767,
    discount: 10,
    category: "Muebles",
    image: "/products/placard-caoba.jpeg",
    featured: true,
    specifications: {
      Material: "Melamina de 15 mm",
      Puertas: "2",
      Cajones: "2 con guías",
      Manijas: "Plástico",
      Barral: "Plástico",
      "Acabado interior": "Mate, no revestido",
      Ancho: "0,57 m",
      Alto: "1,81 m",
      Profundidad: "0,46 m",
      Peso: "40 kg",
      "Colores disponibles": "Caoba, Chocolate, Blanco",
    },
    gallery: [
      "/products/placard-caoba.jpeg",
      "/products/placard-chocolate.jpeg",
      "/products/placard-blanco.jpeg",
      "/products/placard-caoba-abierto.jpeg",
      "/products/dormitorio-caoba.jpeg",
    ],
  },
]

