import type { Product } from "@/lib/types"

export const mueblesProducts: Product[] = [
  {
    id: "columna-cocina-180",
    name: "Columna 1,80 Mts - 1 Puerta y 1 Cajón",
    description:
      "Organizador vertical que te permitirá optimizar el espacio en tu cocina. Con una altura de 1,80 metros, esta columna combina funcionalidad y diseño con su estructura en color blanco y detalles en Carvalho Mezzo. Cuenta con un cajón superior para guardar utensilios y un espacio inferior cerrado con estante para almacenamiento adicional. En su parte superior encontrarás estantes abiertos para tener a mano los elementos de uso frecuente. Ideal para cocinas de cualquier tamaño, este mueble maximiza el espacio vertical sin ocupar demasiada superficie.",
    price: 105881,
    discount: 15,
    category: "Muebles",
    image:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/columna1.png.jpg-1kjU554vHQCCxM5x23wFKO6S9isLPX.jpeg",
    featured: true,
    specifications: {
      Marca: "Mosconi",
      Peso: "26 kg",
      Ancho: "40 cm",
      Color: "Blanco (Carvalho Mezzo)",
      Material: "Melaminico Liso (Liso) Mate",
      Garantía: "6 meses",
      Profundidad: "31 cm",
      "Requiere armado": "SI",
      "Cantidad de cajones": "1",
      "Cantidad de puertas": "1",
      Altura: "180 cm",
    },
    gallery: [
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/columna1.png.jpg-1kjU554vHQCCxM5x23wFKO6S9isLPX.jpeg",
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/columna3.png.jpg-oBnm2pu4cYyRbNTBpJfjwdEZORFxaQ.jpeg",
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/columna2.png.jpg-qmJNcZe0s0ZU1mrkA3VkV9Va1PTS0S.jpeg",
    ],
  },
  {
    id: "alacena-porta-microondas",
    name: "Alacena Porta Microondas 60 cm. Melamina Gabinete Cocina Blanco",
    description:
      "Alacena especialmente diseñada para colocar tu microondas de manera segura y ordenada. Con un ancho de 60 cm, este mueble de melamina en color blanco ofrece un espacio abierto con estante que se adapta perfectamente a la mayoría de los microondas del mercado. Su diseño minimalista y funcional se integra fácilmente en cualquier cocina, optimizando el espacio y manteniendo tus electrodomésticos organizados. Fácil de instalar y limpiar, esta alacena es la solución ideal para liberar espacio en tu mesada.",
    price: 50587,
    discount: 15,
    category: "Muebles",
    image:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/portamicroondas3.png.jpg-2F3x5y7heCjAdAry5ReMmQfJ640QYm.jpeg",
    featured: true,
    specifications: {
      Material: "Melamina",
      Color: "Blanco",
      Ancho: "60 cm",
      "Tipo de mueble": "Alacena porta microondas",
      "Requiere ensamblado": "Sí",
      "Incluye herrajes": "Sí",
      "Tipo de instalación": "A pared",
    },
    gallery: [
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/portamicroondas3.png.jpg-2F3x5y7heCjAdAry5ReMmQfJ640QYm.jpeg",
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/portamicroondas.png.jpg-s5BrHcZ8XvQr3UzO6FLF8qwmXgiL16.jpeg",
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/portamicroondas2.png.jpg-xOcsRx5Gkg1QjdYuyh9YhQDfWwpTWh.jpeg",
    ],
  },
  {
    id: "vajillero-doors-130",
    name: "Vajillero Mosconi Doors 130 Melamina Nebraska Natural/Blanco",
    description:
      "Elegante vajillero de la línea Doors de Mosconi, con un diseño moderno que combina la calidez de la melamina Nebraska Natural con el minimalismo del blanco. Cuenta con 3 puertas batientes y 3 estantes fijos que ofrecen amplio espacio de almacenamiento para vajilla, cristalería y otros elementos del hogar. Sus 5 patas regulables garantizan estabilidad en cualquier superficie, mientras que su capacidad de carga de hasta 80 kg permite almacenar todo tipo de artículos. Ideal para comedores, livings o cocinas, este mueble combina funcionalidad y estética para complementar cualquier estilo de decoración.",
    price: 199999,
    discount: 15,
    category: "Muebles",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/natural.png-SW8L5Qdm0TJNlDOigTYIJxVFR3VbNq.webp",
    featured: true,
    specifications: {
      "Medidas producto armado": "129x77x40 cm",
      "Material principal": "Melamina 15 mm",
      Fondo: "MDF 3 mm",
      Revestimiento: "Blanco",
      Terminación: "Texturado Liso Mate",
      Puertas: "3 - Batientes",
      Estantes: "2 - Fijos Peso max 20 kg, 1 - Fijo Peso max 10 kg",
      Patas: "5 - Regulables",
      "Carga máxima admisible total": "80 kg",
      Color: "Nebraska Natural/Blanco",
    },
    gallery: [
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/natural.png-SW8L5Qdm0TJNlDOigTYIJxVFR3VbNq.webp",
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/natural3.png-8O1wV2KUcnEHzGmF0UwotqsKh1psOV.webp",
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/natural2.png-uiaJex7vhfQfBcuOAiTrop5AlnHIO0.webp",
    ],
  },
  {
    id: "rack-panel-flotante-tv",
    name: "Rack Panel Flotante Para Tv Con Estantes Hasta 55 Pulgadas",
    description:
      "Panel flotante para TV con estantes, diseñado para crear un espacio de entretenimiento moderno y minimalista en tu hogar. Compatible con televisores LED y Smart de 24 a 55 pulgadas, este panel se instala directamente en la pared, eliminando la necesidad de muebles tradicionales y optimizando el espacio disponible. Incluye estantes para colocar equipos multimedia, consolas o elementos decorativos. Su diseño versátil y contemporáneo se adapta a cualquier estilo de decoración, convirtiéndose en el punto focal de tu sala de estar.",
    price: 147647,
    discount: 15,
    category: "Muebles",
    image:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/panelflotante1.png.jpg-7GMUu5xJ8fSXV8x2mglbPOnV8WKhzj.jpeg",
    featured: true,
    specifications: {
      Marca: "Mosconi",
      Modelo: "Panel 129",
      "Tipos de pantallas compatibles": "Led/Smart",
      "Tamaño mínimo de la pantalla": "24 pulgadas",
      "Tamaño máximo de la pantalla": "55 pulgadas",
      "Lugares de montaje": "Pared",
      Medidas: "135x100x30 cm",
      Material: "Melamina",
      "Estándares VESA": "Compatibles",
    },
    gallery: [
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/panelflotante1.png.jpg-7GMUu5xJ8fSXV8x2mglbPOnV8WKhzj.jpeg",
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/panelflotante2.png.jpg-d6jfcFGhVUdaJfaPZlhtvtDSXsJIB1.jpeg",
    ],
  },
  {
    id: "rack-tv-modulo-l",
    name: "Rack Tv Led Mosconi Módulo L Combinable Living Venezia",
    description:
      "Módulo TV Rack L de Mosconi, un mueble versátil y moderno que se adapta a diferentes espacios y necesidades. Fabricado en melamina sobre MDP de 15 mm, cuenta con 3 espacios abiertos para organizar equipos multimedia, consolas o elementos decorativos. Su diseño innovador permite utilizarlo tanto en forma horizontal como vertical, y puede combinarse con otras unidades para crear composiciones personalizadas. Disponible en varios colores como Blanco, Negro, Rojo, Tabaco, Venezia y Wengue, este rack es la solución perfecta para quienes buscan funcionalidad y estilo en su sala de estar.",
    price: 70587,
    discount: 15,
    category: "Muebles",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/modulo1.png-Y38dQksk2aWjW006INcCo8P9Q4jbEs.webp",
    featured: true,
    specifications: {
      Marca: "Mosconi",
      Modelo: "Módulo TV Rack L",
      Colores: "Blanco, Negro, Rojo, Tabaco, Venezia, Wengue",
      Medidas: "136x29x56 cm",
      Material: "Melamina sobre MDP 15 mm",
      Espacios: "3 espacios abiertos",
      Uso: "Horizontal o vertical, combinable con varias unidades",
      "Incluye soporte de TV": "No",
    },
    gallery: [
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/modulo1.png-Y38dQksk2aWjW006INcCo8P9Q4jbEs.webp",
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/modulo2.png-zbmJgICu19OrvuVjHOJQb4U7Mj5Tii.webp",
    ],
  },
  {
    id: "modulo-bajo-mesada-40",
    name: "Módulo Bajo Mesada 40 cm. Express Melamina Gabinete Cocina",
    description:
      "Módulo bajo mesada de 40 cm, diseñado para integrarse perfectamente en tu cocina o ampliar las bajo mesadas existentes. A diferencia de otros modelos, cuenta con una tapa superior de melamina de 15 mm que permite utilizarlo sin necesidad de agregar mármol o acero inoxidable. Incluye un estante regulable interior que maximiza el espacio de almacenamiento y se adapta a tus necesidades. Disponible en color blanco con opción de frente en wengue, este módulo versátil es ideal tanto para cocinas como para lavaderos u otros espacios donde necesites almacenamiento adicional.",
    price: 64705,
    discount: 15,
    category: "Muebles",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/bajo1.png.jpg-drBfsu0WxpfOS6H5zbWTXy3xEP2kxh.jpeg",
    featured: true,
    specifications: {
      Tipo: "Módulo individual bajo mesada",
      Ancho: "40 cm",
      Material: "Melamina",
      "Características especiales": "Tapa superior de melamina 15 mm incluida",
      "Estantes interiores": "1 estante regulable",
      "Colores disponibles": "Blanco con frente Wengue",
      "Usos recomendados": "Cocina, lavadero",
      "Se integra con": "Bajo Mesadas 120, 140 y 160",
    },
    gallery: [
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/bajo1.png.jpg-drBfsu0WxpfOS6H5zbWTXy3xEP2kxh.jpeg",
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/bajo2.png.jpg-JDgRRtPspkR7YA04jUKuXJ0Oq0FIa8.jpeg",
    ],
  },
  {
    id: "cama-fiona-1-plaza",
    name: "Cama Fiona 1 Plaza Infantil Juvenil Melamina Mosconi",
    description:
      "Cama infantil/juvenil de 1 plaza con diseño moderno y funcional, ideal para habitaciones de niños y adolescentes. Fabricada en placa aglomerada de 15 mm pintada con laca UV y molduras de MDF de 22 mm con laca poliuretánica que garantizan durabilidad y resistencia. Su cabecera con detalles calados le da un toque distintivo y elegante. Diseñada para colchón de 190 cm x 80 cm x 17 cm, soporta hasta 100 kg de peso, lo que la hace perfecta para acompañar el crecimiento de los más pequeños.",
    price: 141176,
    discount: 15,
    category: "Muebles",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/fiona1.png-qRyVdjARFhtuYZvNLCz2KxUZS4gtcv.webp",
    featured: true,
    specifications: {
      Marca: "Mosconi",
      Modelo: "Fiona",
      Medidas: "99 cm alto x 196 cm ancho x 90 cm prof",
      Material: "Placa aglomerada 15 mm pintada con laca UV. Molduras MDF 22 mm pintadas con laca poliuretánica",
      "Tamaño de colchón recomendado": "190 cm x 80 cm x 17 cm",
      "Peso máximo soportado": "100 kg",
      "Requiere ensamblado": "Sí",
      Color: "Blanco",
      Estilo: "Moderno",
    },
    gallery: [
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/fiona1.png-qRyVdjARFhtuYZvNLCz2KxUZS4gtcv.webp",
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/fiona.png-zhPVTAt6DA9yoVVWidkV0lW7XvYNRO.webp",
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/camamelamina.png-3o1g9zpBT5ZsEzYJpjYG3feEiK5lFy.webp",
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/camamelamina1.png-gNO4ldGDGuZ5nimtoOIc6GL0H9sYDj.webp",
    ],
  },
  {
    id: "cama-moderna-1-plaza",
    name: "Cama Moderna Melamina 1 Plaza Infantil Juvenil 1.90",
    description:
      "Cama de 1 plaza con diseño clásico y líneas limpias, perfecta para dormitorios infantiles o juveniles. Fabricada en melamina de alta calidad que garantiza durabilidad y resistencia, soportando hasta 140 kg de peso. Su estructura robusta y acabado en color blanco se integra fácilmente con cualquier estilo de decoración. Ideal para colchones de 1 plaza estándar, esta cama combina funcionalidad y estética para crear un espacio de descanso confortable y duradero.",
    price: 152940,
    discount: 15,
    category: "Muebles",
    image:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/camamelamina.png-3o1g9zpBT5ZsEzYJpjYG3feEiK5lFy.webp",
    featured: true,
    specifications: {
      Marca: "Ahorro Compras",
      Modelo: "5",
      "Tipo de cama": "Clásica",
      "Tamaño de la cama": "1 plaza",
      Materiales: "Melamina",
      "Peso máximo soportado": "140 kg",
      Altura: "101 cm",
      "Largo x Ancho": "198 cm x 90 cm",
      "Requiere ensamblado": "Sí",
      Color: "Blanco",
    },
    gallery: [
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/camamelamina.png-3o1g9zpBT5ZsEzYJpjYG3feEiK5lFy.webp",
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/camamelamina1.png-gNO4ldGDGuZ5nimtoOIc6GL0H9sYDj.webp",
    ],
  },
  {
    id: "escritorio-dakar-estantes",
    name: "Escritorio Mesa De Pc Oficina Estudio Living Mosconi Dakar Con Estantes",
    description:
      "Escritorio funcional y moderno de la línea Dakar de Mosconi, ideal para espacios de estudio, oficina o living. Fabricado en MDP de 15 mm en color blanco, cuenta con estantes laterales que proporcionan espacio adicional para organizar libros, documentos o elementos decorativos. Su diseño minimalista y versátil se adapta a cualquier ambiente, mientras que su estructura resistente soporta hasta 50 kg. Perfecto para crear un espacio de trabajo eficiente y ordenado en cualquier rincón de tu hogar.",
    price: 94117,
    discount: 15,
    category: "Muebles",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/mesapc1.png-OxM6TEXSLpxFImwOMceE3ZuXrjsvAo.webp",
    featured: true,
    specifications: {
      Marca: "Mosconi",
      Modelo: "Dakar",
      Largo: "84 cm",
      "Altura x Ancho x Profundidad": "84 cm x 1.01 m x 46 cm",
      Color: "Blanco",
      "Capacidad en peso": "50 kg",
      "Materiales del escritorio": "MDP 15mm",
      Estilo: "Clásico",
      "Requiere ensamblado": "Sí",
    },
    gallery: [
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/mesapc1.png-OxM6TEXSLpxFImwOMceE3ZuXrjsvAo.webp",
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/mesapc2.png-NwvHHM82cz1LlrDOdUbKxuB04iUmaB.webp",
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/mesapc.png.jpg-WI33K4kiEMfZUpld0pRD07CrRyBCXi.jpeg",
    ],
  },
  {
    id: "rack-tv-dakar",
    name: "Rack Mueble De Tv Dakar Melamina Mesa Tv",
    description:
      "Rack para TV de la línea Dakar, diseñado para optimizar el espacio en tu sala de estar o living. Fabricado en melamina de alta calidad, este mueble combina funcionalidad y estética con sus múltiples compartimentos abiertos y una puerta que permite ocultar elementos que prefieras mantener fuera de la vista. Sus dimensiones de 135 cm de ancho, 45 cm de profundidad y 52 cm de altura lo hacen ideal para televisores de diversos tamaños, mientras que su diseño minimalista en tonos claros se integra perfectamente con cualquier estilo de decoración.",
    price: 117646,
    discount: 15,
    category: "Muebles",
    image:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/rackmosconi2.png.jpg-XMloGoA2oytEnnN9oyqgC2iz82Gf5Y.jpeg",
    featured: true,
    specifications: {
      Marca: "Mosconi",
      Modelo: "Dakar",
      "Formato del mueble": "Rack",
      "Material de la estructura": "Melamina",
      "Ancho x Profundidad x Altura": "135 cm x 45 cm x 52 cm",
      "Cantidad de puertas": "1",
      "Requiere ensamblado": "Sí",
      "Con compartimento para parlantes": "No",
      "Con ruedas": "No",
      Color: "Blanco/Madera clara",
    },
    gallery: [
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/rackmosconi2.png.jpg-XMloGoA2oytEnnN9oyqgC2iz82Gf5Y.jpeg",
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/rackmosconi1.png-04KRD31O5Li8khrsMv4xxvR7audDZ9.webp",
    ],
  },
  {
    id: "despensero-2-puertas",
    name: "Mueble de cocina Despensero 2 Puertas",
    description:
      "Despensero de cocina con interior revestido de 1.50 metros de altura, ideal para organizar y almacenar alimentos, vajilla y utensilios. Fabricado en aglomerado revestido color chocolate con puertas en tono oscuro que contrastan con el interior blanco, creando un diseño elegante y funcional. Cuenta con bisagras metálicas de alta resistencia que garantizan durabilidad y un cierre suave. Sus estantes interiores permiten organizar eficientemente todo tipo de productos, desde alimentos envasados hasta vajilla y electrodomésticos pequeños.",
    price: 105881,
    discount: 15,
    category: "Muebles",
    image:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/D_NQ_NP_686212-MLA80820542979_112024-O-xiJsHX05S8hU0RTDnUCmi528mMBx5Z.webp",
    featured: true,
    specifications: {
      Material: "Aglomerado revestido",
      Color: "Chocolate con interior blanco",
      Altura: "1.50 metros",
      Puertas: "2",
      Bisagras: "Metálicas",
      Estantes: "Múltiples niveles para almacenamiento",
      Acabado: "Mate",
      Estilo: "Moderno",
    },
    gallery: [
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/D_NQ_NP_686212-MLA80820542979_112024-O-xiJsHX05S8hU0RTDnUCmi528mMBx5Z.webp",
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/6.png-kWoLsom91Twc9NjryoGp5DV3HAba0G.jpeg",
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/D_NQ_NP_980031-MLA47365232115_092021-O-HDQqSrWaTMRQAvmZvwOtEBGp383Oo0.webp",
    ],
  },
  {
    id: "placard-3-puertas-2-cajones",
    name: "Placard 3 Puertas 2 Cajones Ropero Interior Sin Pintar",
    description:
      "El Placard Super Express de 3 puertas y 2 cajones combina funcionalidad y diseño para maximizar el espacio de almacenamiento en tu dormitorio. Cuenta con un amplio espacio de colgado junto con estantes especialmente diseñados para organizar tu ropa de la manera más conveniente. Fabricado en MDP de 15 mm de alta calidad con fondo de MDF de 3 mm, este placard ofrece durabilidad y resistencia. Sus cajones incluyen correderas metálicas para un deslizamiento suave y mayor durabilidad, con capacidad de hasta 5 kg cada uno. El interior sin pintar permite personalizar el acabado según tus preferencias.",
    price: 164705,
    discount: 15,
    category: "Muebles",
    image:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/D_NQ_NP_824383-MLA80558642220_112024-O-DF1d5pOMMzZk8rnyAeuph2lx04KKNO.webp",
    featured: true,
    specifications: {
      "Material Principal": "MDP 15 mm",
      Fondo: "MDF 3 mm",
      Puertas: "3",
      Cajones: "2 con correderas metálicas (peso máx: 5 kg cada uno)",
      Estantes: "2 fijos (peso máx: 20 kg cada uno), 1 regulable con 1 posición (peso máx: 10 kg)",
      "Carga Máxima Admisible Total": "40 kg",
      Interior: "Sin pintar",
      Exterior: "Revestido",
    },
    gallery: [
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/D_NQ_NP_824383-MLA80558642220_112024-O-DF1d5pOMMzZk8rnyAeuph2lx04KKNO.webp",
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/D_NQ_NP_936441-MLA49954538562_052022-O-h7iUaK3knOT11zeAlFMRayKcHDO0aw.webp",
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/D_NQ_NP_711528-MLA49954512790_052022-O-8YkJkXLaq2q63NIFrLbVJWaTqHet6j.webp",
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/D_NQ_NP_834880-MLA49954576309_052022-O-WJtO7e2kUDIwrahvcudHGJOnm4ffUO.webp",
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/4.png-3lIyb6iaGqh9ymA7UQCD0qldro6glU.jpeg",
    ],
  },
  {
    id: "mesa-luz-dormitorio-1-cajon",
    name: "Mesa De Luz Dormitorio Noche Moderna Melamina 1 Cajon",
    description:
      "Mesa de luz moderna y funcional con un cajón y espacio libre inferior, ideal para dormitorios. Fabricada en MDP de 15 mm con acabado mate, esta mesa de luz de la línea Dakar Zero de Mosconi combina practicidad y estilo. Su diseño clásico con patas incluye un cajón con correderas metálicas y manija plástica para almacenar tus objetos personales, mientras que el espacio inferior abierto ofrece versatilidad adicional. Disponible en color claro, se adapta perfectamente a cualquier estilo de decoración.",
    price: 38822,
    discount: 15,
    category: "Muebles",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/uncajon.png-vdJvEF8jAFR9v5zpV6mTDti7C7oBf0.webp",
    featured: true,
    specifications: {
      Marca: "Mosconi",
      Línea: "Dakar Zero",
      Modelo: "1 Cajon - Espacio libre",
      "Material de la mesa de luz": "MDP 15 mm",
      Altura: "56 cm",
      Ancho: "38 cm",
      Profundidad: "38 cm",
      "Cantidad de mesas de luz": "1",
      Acabado: "Mate",
      Peso: "10 kg",
      Estilo: "Clásico",
      "Tipo de mesa de luz": "Con patas",
      "Material de las bisagras": "Metal",
      "Con cajones": "Sí",
      "Cantidad de cajones": "1",
      "Con correderas": "Sí",
      "Material de las correderas": "METAL",
      "Con manija": "Sí",
      "Material de la manija": "Plástico",
      "Requiere ensamblado": "Sí",
      "Con bandeja extraíble": "No",
      "Con estantes": "No",
      "Con puertas": "Sí",
      "Con ruedas": "No",
      "Es personalizado": "No",
      "Incluye herramientas para armado": "Sí",
    },
    gallery: [
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/uncajon.png-vdJvEF8jAFR9v5zpV6mTDti7C7oBf0.webp",
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/uncajon1.png-Sye9S4Vtw1vsKgkQK9mpKGPrllndwz.webp",
    ],
  },
  {
    id: "zapatero-3-puertas",
    name: "Mueble Zapatero Organizador De Zapatos Melamina",
    description:
      "Zapatero moderno de 3 puertas, diseñado para organizar tu calzado de manera eficiente y elegante. Con capacidad para 15 a 18 pares de zapatos (hasta talle 42), este mueble optimiza el espacio en tu hogar mientras mantiene tu calzado ordenado y protegido del polvo. Fabricado con melamina MDP de 15mm de grosor y fondo de MDF de 3mm, ofrece durabilidad y resistencia. Sus puertas tienen un sistema de apertura y cierre suave que garantiza comodidad y funcionalidad. Ideal para pasillos, dormitorios o vestidores.",
    price: 141175,
    discount: 15,
    category: "Muebles",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/zapatero2.png-dvgxV1BjaPDJDPnnljaUJKTF560TaO.webp",
    featured: true,
    specifications: {
      Producto: "Zapatero 3 Puertas",
      Material: "Melamina MDP 15mm, fondo MDF 3mm",
      Capacidad: "15-18 pares de zapatos (hasta talle 42)",
      Ancho: "62 cm",
      Profundidad: "22 cm",
      Altura: "121 cm",
      "Medidas de embalaje": "50 x 9 x 123 cm",
      "Peso del paquete": "27 kg",
      Características: "Puertas con cierre y apertura suave",
      Color: "Blanco",
    },
    gallery: [
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/zapatero2.png-dvgxV1BjaPDJDPnnljaUJKTF560TaO.webp",
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/zapatero3.png-BU0LGXkpjXKI9sxjYpeHH319ibfRYA.webp",
    ],
  },
  {
    id: "mesa-luz-flotante-benethon",
    name: "Mesa De Luz Flotante Benethon Moderna Mosconi",
    description:
      "Mesa de luz flotante de diseño moderno de la línea Benethon de Mosconi, ideal para optimizar el espacio en dormitorios contemporáneos. Se instala directamente a la pared, eliminando la necesidad de patas y creando una sensación de amplitud en la habitación. Cuenta con un cajón con correderas metálicas y manija plástica para almacenar objetos personales. Fabricada en melamina con acabado brillante, esta mesa de luz combina funcionalidad y estética minimalista, convirtiéndose en un elemento decorativo por sí misma.",
    price: 64118,
    discount: 15,
    category: "Muebles",
    image:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/flotante2.png.jpg-B4USTWfpCiP1SsBwKMLicx9vefnw7K.jpeg",
    featured: true,
    specifications: {
      Marca: "Mosconi",
      Línea: "Benethon",
      Modelo: "Benethon",
      "Material de la mesa de luz": "Melamina",
      Altura: "90 cm",
      Ancho: "45 cm",
      Profundidad: "41 cm",
      Acabado: "Brillante",
      Peso: "12 kg",
      Estilo: "Moderno",
      "Tipo de mesa de luz": "Con 1 Cajon",
      "Con cajones": "Sí",
      "Cantidad de cajones": "1",
      "Con correderas": "Sí",
      "Material de las correderas": "Metálicas",
      "Con manija": "Sí",
      "Material de la manija": "Plástico",
      "Requiere ensamblado": "Sí",
      "Con puertas": "No",
      "Con ruedas": "No",
    },
    gallery: [
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/flotante2.png.jpg-B4USTWfpCiP1SsBwKMLicx9vefnw7K.jpeg",
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/flotante4.png-ClgpFCh1G76JYTHlCck1Hc8otnYyra.webp",
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/flotante1.png.jpg-hSnU7yFfIeTE75uHuM8y8OWlJhh2av.jpeg",
    ],
  },
  {
    id: "comoda-super-express",
    name: "Cómoda Cajonera Súper Express Mosconi 4 Cajones / 1 Puerta",
    description:
      "Cómoda multifuncional con 4 cajones y 1 puerta, ideal para dormitorios o salas de estar. Fabricada en MDP de 15 mm con terminación UV, disponible en colores Caoba, Chocolate y Roble. Sus 4 cajones con correderas plásticas ofrecen amplio espacio de almacenamiento, mientras que la puerta lateral incluye un estante de altura regulable para mayor versatilidad. Las manijas plásticas color gris complementan su diseño elegante y funcional.",
    price: 111764,
    discount: 15,
    category: "Muebles",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/comoda1.png-FpL6W5nEFdkaPUZ5IvZbWnCW681S0p.webp",
    featured: true,
    specifications: {
      Marca: "Mosconi",
      Modelo: "Super Express",
      "Tipo de mueble": "Cómoda",
      Medidas: "90x39x91 cm",
      Peso: "36 kg",
      "Material del cuerpo": "MDP 15 mm pintado con terminación UV",
      "Cantidad de cajones": "4 con correderas plásticas",
      "Cantidad de puertas": "1 con estante de altura regulable",
      "Incluye manual de ensamblado": "Sí",
      Manijas: "Plásticas color gris",
      "Colores disponibles": "Caoba, Chocolate, Roble",
    },
    gallery: [
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/comoda1.png-FpL6W5nEFdkaPUZ5IvZbWnCW681S0p.webp",
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/comoda2.png-rNy5onR0iQQjw8vnMa1yODzVDzJojj.webp",
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/comoda.png-TO3YcMNsHWyguLQXDC95aoUTsyVYgb.webp",
    ],
  },
  {
    id: "mesa-centro-nordica",
    name: "Mesa De Centro Melamina Nordica Patas De Hierro",
    description:
      "Mesa de centro con diseño nórdico modelo 'Ayohuma', que combina la calidez de la melamina con la elegancia industrial de las patas de hierro tipo horquilla. Su diseño rectangular con compartimentos de almacenamiento la convierte en una pieza funcional y decorativa para cualquier sala de estar. La combinación de materiales y su acabado mate crean un mueble versátil que se adapta perfectamente a diferentes estilos de decoración.",
    price: 99999,
    discount: 15,
    category: "Muebles",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/mesacentro.png-tODVJy9DwW2bA3gyg2to96IFIwOdLM.webp",
    featured: true,
    specifications: {
      Marca: "Mosconi",
      Modelo: "Mesa Centro Nórdica 'Ayohuma'",
      "Material de la base": "Hierro",
      "Material de la tapa": "Melamina",
      Acabado: "Mate",
      Forma: "Rectangular",
      Altura: "7 cm",
      Largo: "90 cm",
      Ancho: "45 cm",
      Diámetro: "45 cm",
      Peso: "14 kg",
      "Requiere ensamblado": "Sí",
      "Es extensible": "No",
    },
    gallery: [
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/mesacentro.png-tODVJy9DwW2bA3gyg2to96IFIwOdLM.webp",
    ],
  },
  {
    id: "vajillero-doors-170",
    name: "Vajillero 4 Puertas Bahiut Doors Mosconi",
    description:
      "Elegante vajillero de la línea Milenial de Mosconi, con un diseño moderno que combina funcionalidad y estética. Cuenta con 4 puertas de apertura batiente y 3 estantes fijos que ofrecen amplio espacio de almacenamiento para vajilla, cristalería y otros elementos del hogar. Disponible en diversas combinaciones de colores como Nebraska Gris con frente Blanco o Negro, Nebraska Natural con frente Blanco o Negro, y Venezia con frente Blanco. Sus 5 patas regulables de plástico negro garantizan estabilidad en cualquier superficie.",
    price: 247058,
    discount: 15,
    category: "Muebles",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/vajillero3.png-0EwgXr8JQ8eiVUVQzTEnhqQZtkVCIx.webp",
    featured: true,
    specifications: {
      Fabricante: "Mosconi",
      Marca: "Mosconi",
      Línea: "MILENIAL",
      Modelo: "DOORS",
      Acabado: "Mate",
      Estilo: "Clásico",
      Materiales: "Madera",
      "Ancho x Largo x Profundidad": "170 cm x 77 cm x 40 cm",
      Peso: "44 kg",
      "Peso máximo soportado": "80 kg",
      "Cantidad de cajones": "0",
      "Cantidad de puertas": "4 (apertura batiente)",
      "Cantidad de estantes": "3 fijos",
      "Requiere ensamblado": "Sí",
      "Con manija": "No",
      "Con correderas": "No",
      "Colores disponibles":
        "Nebraska Gris fr. Blanco - Nebraska Gris fr. Negro - Nebraska Natural fr. Blanca - Nebraska Natural fr. Negro - Venezia fr Blanco",
    },
    gallery: [
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/vajillero3.png-0EwgXr8JQ8eiVUVQzTEnhqQZtkVCIx.webp",
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/vajillero2.png-4kUQEAKuvfDstKtNeqaxVs9hYfQrnK.webp",
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/vajillero1.png-BlZXA48V2JlGf7sBrh0ZqDRX9diFed.webp",
    ],
  },
  {
    id: "escritorio-computacion-709",
    name: "Escritorio De Computacion 709 Melamina Blanco - MOSCONI",
    description:
      "Escritorio de computación funcional y espacioso, ideal para estudiar o trabajar desde casa. Fabricado en melamina sobre MDP de 15 mm en color blanco, cuenta con una bandeja deslizable para teclado con correderas metálicas y una repisa con 2 estantes para organizar tus elementos de trabajo. Su diseño optimiza el espacio y es compatible con monitores de hasta 19 pulgadas. Disponible también en colores Venezia, Tabaco y Wengue para adaptarse a diferentes estilos de decoración.",
    price: 147058,
    discount: 15,
    category: "Muebles",
    image:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/MKT0369MOS-2.png.jpg-CCynZyX5gI0ViH4kU91VxlFuFGC1T9.jpeg",
    featured: true,
    specifications: {
      Material: "Melamina sobre MDP 15 mm",
      Color: "Blanco",
      "Colores disponibles": "Venezia, Tabaco, Wengue, Blanco",
      "Medidas (Al x An x Prof)": "121 cm x 101 cm x 45 cm",
      Características: "Bandeja deslizable para teclado con correderas metálicas, Repisa con 2 estantes",
      "Compatible con": "Monitor hasta 19 pulgadas",
      Marca: "Mosconi",
      "Peso del paquete": "25 kg",
      "Medidas del paquete": "105x47x14 cm",
    },
    gallery: [
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/MKT0369MOS-2.png.jpg-CCynZyX5gI0ViH4kU91VxlFuFGC1T9.jpeg",
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/MKT0369MOS-1.png.jpg-gp7lJdm4O56y4YfyhBlHKY2uZyvbad.jpeg",
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/MKT0369MOS-3.png.jpg-U2YoiiE7JBPsvuRBk2TJvf5ixVP5SR.jpeg",
    ],
  },
  {
    id: "mueble-organizador-planchado",
    name: "Mueble Organizador De Planchado Mosconi Blanco",
    description:
      "Práctico mueble organizador de planchado con superficie de planchar acolchada color verde. Fabricado en melamina sobre MDP de 15 mm en color blanco, cuenta con 2 puertas con bisagras a resorte y 1 estante interior para almacenar productos de limpieza y planchado. Incluye soporte para plancha y posee ruedas para facilitar su traslado, lo que lo convierte en una solución funcional y móvil para optimizar el espacio en tu hogar.",
    price: 116470,
    discount: 15,
    category: "Muebles",
    image:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/D_NQ_NP_965191-MLA71413428959_082023-O-4LtZEWI6ShZAgjrpdKLZIvhw3uQcKs.webp",
    featured: true,
    specifications: {
      Fabricante: "Mosconi",
      Medidas: "111x36x88 cm",
      Color: "Blanco",
      Material: "Melamina sobre MDP 15 mm",
      Características: "2 puertas con bisagras a resorte y 1 estante",
      Adicionales: "Soporte para plancha, Manijas plásticas color gris, Ruedas para traslado",
    },
    gallery: [
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/D_NQ_NP_965191-MLA71413428959_082023-O-4LtZEWI6ShZAgjrpdKLZIvhw3uQcKs.webp",
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/D_NQ_NP_815133-MLA71369617322_082023-O-otPbKqtiwY7j95p6c2E8UgHL4KfScz.webp",
    ],
  },
  {
    id: "comoda-4-cajones-1-puerta",
    name: "Cómoda 4 Cajones/1 Puerta Express",
    description:
      "Cómoda multifuncional con 4 cajones y 1 puerta, ideal para dormitorios infantiles o juveniles. Fabricada en MDP de 15 mm con terminación UV en color blanco. Los cajones cuentan con correderas plásticas y manijas en colores blanco, rosa y azul que le dan un toque alegre y moderno. La puerta incluye un estante de altura regulable para mayor versatilidad de almacenamiento. Su diseño compacto y funcional optimiza el espacio en cualquier habitación.",
    price: 140000,
    discount: 15,
    category: "Muebles",
    image:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/D_NQ_NP_863850-MLA53141542952_012023-O-62oD7JDNp5Bbm4mvYXOObrlVZkW3mi.webp",
    featured: true,
    specifications: {
      Fabricante: "Mosconi",
      Medidas: "101x48x102 cm",
      Color: "Blanco",
      Material: "MDP 15 mm pintado con terminación UV",
      Cajones: "4 con correderas plásticas",
      "Profundidad del cajón": "42 cm",
      Puerta: "1 con estante de altura regulable",
      Manijas: "Plásticas color blanco, rosa y azul",
    },
    gallery: [
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/D_NQ_NP_863850-MLA53141542952_012023-O-62oD7JDNp5Bbm4mvYXOObrlVZkW3mi.webp",
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/D_NQ_NP_913567-MLA53141542953_012023-O-XwaNalyLVPaNAwrwozJ3wgKe4PaVLy.webp",
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/D_NQ_NP_871584-MLA53141542955_012023-O-Byik4D5qlQesefE3sCIyrRceLXoB65.webp",
    ],
  },
  {
    id: "chifonier-5-cajones-chocolate",
    name: "Chifonier 5 Cajones Pack Color Chocolate",
    description:
      "Chifonier de 5 cajones con diseño funcional y elegante en color chocolate. Fabricado en MDP de 15 mm con revestimiento acrílico UV que garantiza mayor durabilidad y resistencia. Sus 5 cajones con correderas plásticas y manijas color gris plata ofrecen amplio espacio de almacenamiento para ropa y accesorios. Con una carga máxima admisible de 50 kg, este mueble combina practicidad y estética para complementar cualquier dormitorio.",
    price: 82352,
    discount: 15,
    category: "Muebles",
    image:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/D_NQ_NP_724547-MLA82350528671_022025-O-iHydAFsvwLr5tQJiLubV2BNCTPcffg.webp",
    featured: false,
    specifications: {
      "Material Principal": "MDP 15 mm impreso",
      Revestimiento: "Acrílico UV",
      Fondo: "MDF 3 mm",
      Cajones: "5 con peso admisible de 5 kg cada uno",
      Correderas: "Plásticas",
      Manijas: "Plásticas Gris Plata",
      "Carga Máxima Admisible": "50 kg",
      Largo: "91 cm",
      Ancho: "58 cm",
      Profundidad: "38 cm",
      "Colores disponibles": "Chocolate, Caoba, Tissa(Venezia), Mendra, Grei(Nebraska Gris), Blanco, Bambu",
    },
    gallery: [
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/D_NQ_NP_724547-MLA82350528671_022025-O-iHydAFsvwLr5tQJiLubV2BNCTPcffg.webp",
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/D_NQ_NP_770787-MLA82068221932_022025-O-8HqXFcY3OIK0BWW0QRxSDrMROJqMcu.webp",
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/D_NQ_NP_941673-MLA82350413031_022025-O-cYL8RVNydPX25kaIyjD70iB2Vgelg4.webp",
    ],
  },
  {
    id: "placard-6-puertas-2-cajones",
    name: "Ropero Placard 6 Puertas 2 Cajones Dakar Zero Melamina",
    description:
      "Amplio placard de 6 puertas y 2 cajones, perfecto para maximizar el espacio de almacenamiento en tu dormitorio. Fabricado en melamina sobre MDP de 15 mm, disponible en diversos acabados como Carvalho Mezzo frente Blanco, Wengue, Blanco, Tabaco y Venezia. Cuenta con un espacio interior de colgado con barral plástico, 3 estantes fijos y 1 regulable para organizar tu ropa de manera eficiente. Los cajones incluyen correderas metálicas para un deslizamiento suave y mayor durabilidad.",
    price: 258823,
    discount: 15,
    category: "Muebles",
    image:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/D_NQ_NP_888783-MLA49010106997_022022-O-VoP1DHzM7t2bOhH9bByfJ7qrQlt3qc.webp",
    featured: true,
    specifications: {
      Marca: "Mosconi",
      Modelo: "PLACARD 26 DAKAR ZERO",
      Medidas: "169x46x181 cm",
      Material: "Melamina sobre MDP 15 mm",
      Puertas: "6",
      Cajones: "2 con correderas metálicas",
      "Espacio interior": "Barral plástico para colgado, 3 estantes fijos y 1 regulable",
      "Interior y fondo": "Sin pintar",
      Manijas: "Plásticas color gris",
      "Peso máximo por cajón": "5 kg",
      "Medidas interior del cajón": "34x49x11 cm",
      "Colores disponibles": "Carvalho Mezzo frente Blanco, Wengue, Blanco, Tabaco, Venezia",
    },
    gallery: [
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/D_NQ_NP_888783-MLA49010106997_022022-O-VoP1DHzM7t2bOhH9bByfJ7qrQlt3qc.webp",
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/D_NQ_NP_796826-MLA49010106991_022022-O-62fVJL4gAmaLD3Hgfj2JiT28OlJsKi.webp",
    ],
  },
  {
    id: "mueble-apoyo-cocina",
    name: "Mueble Apoyo Cocina Con Ruedas Frutero P/ Microondas",
    description:
      "Mueble multifuncional para cocina con ruedas, ideal para optimizar el espacio en tu hogar. Cuenta con un cajón superior para utensilios, tres bandejas extraíbles plásticas para frutas o verduras, y un compartimento con puerta y estante para almacenamiento adicional. Su superficie superior es perfecta para colocar un microondas u otros electrodomésticos. Las ruedas facilitan su movilidad, permitiéndote ubicarlo donde más lo necesites.",
    price: 85000,
    discount: 0,
    category: "Muebles",
    image: "/products/mueble-cocina-1.png",
    featured: true,
    specifications: {
      Funcionalidad: "Multifunción",
      Características: "Frutero (3 bandejas extraíbles plásticas), Porta microondas, 1 cajón, 1 puerta con estante",
      Movilidad: "Con ruedas",
      Ancho: "0,68 m",
      Alto: "0,91 m",
      Profundidad: "0,40 m",
      Material: "Melamina",
      Color: "Blanco",
    },
    gallery: ["/products/mueble-cocina-1.png", "/products/mueble-cocina-2.png", "/products/mueble-cocina-3.png"],
  },
  {
    id: "barra-desayuno-milano",
    name: "Barra Desayuno Milano 120X44X89 Cm Negro/Roble Dielfe",
    description:
      "La Barra Desayuno Milano de Dielfe es una opción elegante y funcional para su cocina o área de comedor. Con dimensiones de 120x44x89 cm, esta barra está diseñada para ofrecer un espacio cómodo y estilizado para disfrutar de desayunos, comidas rápidas o reuniones informales. El diseño en negro y roble combina la sofisticación del negro con la calidez del roble, creando un contraste atractivo y moderno que se adapta a diversos estilos decorativos. Su diseño compacto y vertical es ideal para espacios más reducidos, maximizando el uso del área disponible sin comprometer la funcionalidad.",
    price: 139000,
    discount: 0,
    category: "Muebles",
    image: "/products/barra-milano-1.jpeg",
    featured: true,
    specifications: {
      "Tipo de Producto": "Desayunadores",
      Color: "Marrón",
      Acabado: "Mate",
      Tono: "Natural-Negro",
      Alto: "89 Cm",
      Ancho: "44,5 Cm",
      Largo: "120 Cm",
      Peso: "12 Kg",
      Extensible: "No",
      Material: "Melamina",
      "Requiere Armado": "Si",
      "Más Información":
        "La barra desayunadora milano tiene un estilo moderno, con líneas simples, dentro de sus características destacamos sus patas metálicas con tubo de sección que no solo le aporta estética, sino que también resistencia, ideal para todo tipo de ambientes.",
      Origen: "Nacional",
      "País de Origen": "Argentina",
      Modelo: "MLD120",
    },
    gallery: ["/products/barra-milano-1.jpeg", "/products/barra-milano-2.jpeg", "/products/barra-milano-3.jpeg"],
  },
  {
    id: "mesa-luz-nordica",
    name: "Mesa De Luz Nórdica Escandinava",
    description:
      "Mesa de luz con diseño nórdico/escandinavo que combina funcionalidad y estética minimalista. Cuenta con un cajón superior y un compartimento inferior con puerta rebatible que proporcionan amplio espacio de almacenamiento para tus objetos personales. Fabricada en madera de pino natural sin tratamiento, esta pieza aporta calidez y un toque contemporáneo a cualquier dormitorio. Sus patas inclinadas le dan un aspecto moderno y distintivo, ideal para espacios con estilo escandinavo.",
    price: 50000,
    discount: 0,
    category: "Muebles",
    image: "/products/mesa-luz-escandinava-1.webp",
    featured: true,
    specifications: {
      Material: "Madera natural",
      Acabado: "Sin lustre",
      Almacenamiento: "1 cajón + puerta rebatible",
      Alto: "60 cm",
      Ancho: "40 cm",
      Profundidad: "30 cm",
      Estilo: "Nórdico/Escandinavo",
    },
    gallery: [
      "/products/mesa-luz-escandinava-1.webp",
      "/products/mesa-luz-escandinava-2.webp",
      "/products/mesa-luz-escandinava-3.webp",
    ],
  },
  {
    id: "modulo-escandinavo",
    name: "Módulo Escandinavo LE075",
    description:
      "El módulo de dos cuerpos de la línea Escandinava, se caracteriza por su estilo minimalista. El diseño está compuesto por un cuerpo principal de melanina y patas de PVC. Este mueble posee seis divisiones internas, dos cerradas con puertas y cuatro libres. Con terminaciones en color blanco combinado con roble bardolino y tiradores de color plateado los cuales acompañan con la estética discreta del diseño. Este módulo se puede adaptar perfectamente al ambiente en el que se lo utilice.",
    price: 99000,
    discount: 0,
    category: "Muebles",
    image: "/products/modulo-escandinavo.png",
    featured: true,
    specifications: {
      "Material del Producto": "Melamina",
      "Cantidad de puertas": "2",
      "Cantidad de estantes": "6",
      "Cantidad de cajones": "0",
      Manijas: "2",
      Medidas: "132*75*30",
      "Requiere armado": "Sí",
      Color: "Blanco con roble",
    },
    gallery: [
      "/products/modulo-escandinavo.png",
      "/products/modulo-escandinavo-2.png",
      "/products/modulo-escandinavo-3.png",
    ],
  },
  {
    id: "silla-escandinava",
    name: "SILLA ESCANDINAVA BOLONIA CAÑO BLANCO TAPIZADO GRIS",
    description:
      "La silla Bolonia combina estilo y confort en un diseño escandinavo elegante y funcional. Su estructura de caño blanco aporta resistencia y estabilidad, mientras que su asiento tapizado en gris brinda comodidad y sofisticación. El respaldo de madera añade un toque cálido y natural, ideal para integrarse en diferentes espacios.",
    price: 55000,
    discount: 0,
    category: "Muebles",
    image: "/products/silla-escandinava.png",
    featured: true,
    specifications: {
      Diseño: "Escandinavo",
      Estructura: "Caño blanco",
      Asiento: "Tapizado en gris",
      Respaldo: "Madera",
      Alto: "84,5 cm",
      Ancho: "43,5 cm",
      Profundidad: "46 cm",
    },
    gallery: ["/products/silla-escandinava.png", "/products/silla-escandinava-2.png"],
  },
  {
    id: "silla-escandinava-negra",
    name: "SILLA ESCANDINAVA BOLONIA CAÑO NEGRO TAPIZADO PLOMO",
    description:
      "La silla Bolonia combina estilo y confort en un diseño escandinavo elegante y funcional. Su estructura de caño negro aporta resistencia y estabilidad, mientras que su asiento tapizado en gris plomo brinda comodidad y sofisticación. El respaldo de madera añade un toque cálido y natural, ideal para integrarse en diferentes espacios.",
    price: 55000,
    discount: 0,
    category: "Muebles",
    image: "/products/silla-bolonia-negra-1.png",
    featured: false,
    specifications: {
      Diseño: "Escandinavo, moderno y versátil",
      Estructura: "Caño negro, resistente y duradera",
      Asiento: "Tapizado en gris plomo, cómodo y fácil de combinar",
      Respaldo: "Madera, aportando un toque natural",
      "Uso recomendado": "Comedores, livings, oficinas o espacios de reunión",
      Alto: "84,5 cm",
      Ancho: "43,5 cm",
      Profundidad: "46 cm",
    },
    gallery: ["/products/silla-bolonia-negra-1.png", "/products/silla-bolonia-negra-2.png"],
  },
  {
    id: "mesa-puket",
    name: "Mesa Puket Auxiliar",
    description:
      "Mesa de diseño redondeado modelo Puket, pensada para ser utilizada al exterior, fabricada con material resistente y duradero. Disponible en color blanco y gris. Todos nuestros productos plásticos son fáciles de limpiar, resistentes a los rayos UV y están elaborados para que no dañen el ambiente.",
    price: 17000,
    discount: 0,
    category: "Muebles",
    image: "/products/mesa-puket-blanca.jpeg",
    featured: false,
    specifications: {
      Material: "Plástico resistente",
      Uso: "Interior y exterior",
      "Resistente a rayos UV": "Sí",
      "Fácil limpieza": "Sí",
      "Colores disponibles": "Blanco, Gris",
      Diseño: "Redondeado",
    },
    gallery: ["/products/mesa-puket-blanca.jpeg", "/products/mesa-puket-gris.webp"],
  },
  {
    id: "mesa-luz-1-puerta-1-cajon",
    name: "Mesa de Luz 1 Puerta 1 Cajón",
    description:
      "Mesa de luz funcional y moderna con un cajón y una puerta, ideal para el dormitorio. Fabricada en MDP de 15 mm impreso con revestimiento acrílico UV que garantiza durabilidad y resistencia. Disponible en colores blanco y chocolate, se adapta perfectamente a cualquier estilo de decoración. Sus medidas compactas (56 cm de alto, 38 cm de ancho y 37 cm de profundidad) la hacen perfecta para espacios reducidos.",
    price: 47058,
    discount: 15,
    category: "Muebles",
    image: "/products/mesa-luz-chocolate.jpeg",
    featured: true,
    specifications: {
      "Material principal": "MDP 15 mm impreso",
      Fondo: "MDF 3 mm",
      Revestimiento: "Acrílico UV",
      Cajones: "1",
      Puertas: "1",
      Manijas: "Plástico (Gris Plata)",
      "Correderas de cajones": "Plásticas",
      "Carga admisible total": "15 kg",
      Alto: "0,56 m",
      Ancho: "0,38 m",
      Profundidad: "0,37 m",
      "Colores disponibles": "Blanco, Chocolate",
    },
    gallery: [
      "/products/mesa-luz-chocolate.jpeg",
      "/products/mesa-luz-blanca.jpeg",
      "/products/mesa-luz-chocolate-abierta.jpeg",
      "/products/mesa-luz-blanca-abierta.jpeg",
      "/products/mesa-luz-blanca-ambiente.jpeg",
    ],
  },
  {
    id: "placard-2-puertas-2-cajones",
    name: "Placard 2 Puertas 2 Cajones",
    description:
      "Placard funcional y espacioso con dos puertas y dos cajones, perfecto para organizar tu ropa y accesorios. Fabricado en melamina de 15 mm que garantiza durabilidad y resistencia. Disponible en colores caoba, chocolate y blanco para adaptarse a cualquier estilo de decoración. Sus dimensiones (1,81 m de alto, 0,57 m de ancho y 0,46 m de profundidad) ofrecen amplio espacio de almacenamiento sin ocupar demasiado espacio en la habitación.",
    price: 81248,75,
    discount: 20,
    category: "Muebles",
    image: "/products/placard-caoba.jpeg",
    featured: true,
    specifications: {
      Material: "Melamina de 15 mm",
      Puertas: "2",
      Cajones: "2 con guías",
      Manijas: "Plástico",
      Barral: "Plástico",
      "Acabado interior": "Mate, no revestido",
      Ancho: "0,57 m",
      Alto: "1,81 m",
      Profundidad: "0,46 m",
      Peso: "40 kg",
      "Colores disponibles": "Caoba, Chocolate, Blanco",
    },
    gallery: [
      "/products/placard-caoba.jpeg",
      "/products/placard-chocolate.jpeg",
      "/products/placard-blanco.jpeg",
      "/products/placard-caoba-abierto.jpeg",
      "/products/dormitorio-caoba.jpeg",
    ],
  },
]
