import type { Product } from "@/lib/types"

export const mueblesProducts: Product[] = [
  {
    id: "comoda-super-express",
    name: "Cómoda Cajonera Súper Express Mosconi 4 Cajones / 1 Puerta",
    description:
      "Cómoda multifuncional con 4 cajones y 1 puerta, ideal para dormitorios o salas de estar. Fabricada en MDP de 15 mm con terminación UV, disponible en colores Caoba, Chocolate y Roble. Sus 4 cajones con correderas plásticas ofrecen amplio espacio de almacenamiento, mientras que la puerta lateral incluye un estante de altura regulable para mayor versatilidad. Las manijas plásticas color gris complementan su diseño elegante y funcional.",
    price: 111764,
    discount: 15,
    category: "Muebles",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/comoda1.png-FpL6W5nEFdkaPUZ5IvZbWnCW681S0p.webp",
    featured: true,
    specifications: {
      Marca: "Mosconi",
      Modelo: "Super Express",
      "Tipo de mueble": "Cómoda",
      Medidas: "90x39x91 cm",
      Peso: "36 kg",
      "Material del cuerpo": "MDP 15 mm pintado con terminación UV",
      "Cantidad de cajones": "4 con correderas plásticas",
      "Cantidad de puertas": "1 con estante de altura regulable",
      "Incluye manual de ensamblado": "Sí",
      Manijas: "Plásticas color gris",
      "Colores disponibles": "Caoba, Chocolate, Roble",
    },
    gallery: [
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/comoda1.png-FpL6W5nEFdkaPUZ5IvZbWnCW681S0p.webp",
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/comoda2.png-rNy5onR0iQQjw8vnMa1yODzVDzJojj.webp",
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/comoda.png-TO3YcMNsHWyguLQXDC95aoUTsyVYgb.webp",
    ],
  },
  {
    id: "mesa-centro-nordica",
    name: "Mesa De Centro Melamina Nordica Patas De Hierro",
    description:
      "Mesa de centro con diseño nórdico modelo 'Ayohuma', que combina la calidez de la melamina con la elegancia industrial de las patas de hierro tipo horquilla. Su diseño rectangular con compartimentos de almacenamiento la convierte en una pieza funcional y decorativa para cualquier sala de estar. La combinación de materiales y su acabado mate crean un mueble versátil que se adapta perfectamente a diferentes estilos de decoración.",
    price: 88235,
    discount: 15,
    category: "Muebles",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/mesacentro.png-tODVJy9DwW2bA3gyg2to96IFIwOdLM.webp",
    featured: true,
    specifications: {
      Marca: "Mosconi",
      Modelo: "Mesa Centro Nórdica 'Ayohuma'",
      "Material de la base": "Hierro",
      "Material de la tapa": "Melamina",
      Acabado: "Mate",
      Forma: "Rectangular",
      Altura: "7 cm",
      Largo: "90 cm",
      Ancho: "45 cm",
      Diámetro: "45 cm",
      Peso: "14 kg",
      "Requiere ensamblado": "Sí",
      "Es extensible": "No",
    },
    gallery: [
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/mesacentro.png-tODVJy9DwW2bA3gyg2to96IFIwOdLM.webp",
    ],
  },
  {
    id: "vajillero-doors-170",
    name: "Vajillero 4 Puertas Bahiut Doors Mosconi",
    description:
      "Elegante vajillero de la línea Milenial de Mosconi, con un diseño moderno que combina funcionalidad y estética. Cuenta con 4 puertas de apertura batiente y 3 estantes fijos que ofrecen amplio espacio de almacenamiento para vajilla, cristalería y otros elementos del hogar. Disponible en diversas combinaciones de colores como Nebraska Gris con frente Blanco o Negro, Nebraska Natural con frente Blanco o Negro, y Venezia con frente Blanco. Sus 5 patas regulables de plástico negro garantizan estabilidad en cualquier superficie.",
    price: 200000,
    discount: 15,
    category: "Muebles",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/vajillero3.png-0EwgXr8JQ8eiVUVQzTEnhqQZtkVCIx.webp",
    featured: true,
    specifications: {
      Fabricante: "Mosconi",
      Marca: "Mosconi",
      Línea: "MILENIAL",
      Modelo: "DOORS",
      Acabado: "Mate",
      Estilo: "Clásico",
      Materiales: "Madera",
      "Ancho x Largo x Profundidad": "170 cm x 77 cm x 40 cm",
      Peso: "44 kg",
      "Peso máximo soportado": "80 kg",
      "Cantidad de cajones": "0",
      "Cantidad de puertas": "4 (apertura batiente)",
      "Cantidad de estantes": "3 fijos",
      "Requiere ensamblado": "Sí",
      "Con manija": "No",
      "Con correderas": "No",
      "Colores disponibles":
        "Nebraska Gris fr. Blanco - Nebraska Gris fr. Negro - Nebraska Natural fr. Blanca - Nebraska Natural fr. Negro - Venezia fr Blanco",
    },
    gallery: [
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/vajillero3.png-0EwgXr8JQ8eiVUVQzTEnhqQZtkVCIx.webp",
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/vajillero2.png-4kUQEAKuvfDstKtNeqaxVs9hYfQrnK.webp",
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/vajillero1.png-BlZXA48V2JlGf7sBrh0ZqDRX9diFed.webp",
    ],
  },
  {
    id: "escritorio-computacion-709",
    name: "Escritorio De Computacion 709 Melamina Blanco - MOSCONI",
    description:
      "Escritorio de computación funcional y espacioso, ideal para estudiar o trabajar desde casa. Fabricado en melamina sobre MDP de 15 mm en color blanco, cuenta con una bandeja deslizable para teclado con correderas metálicas y una repisa con 2 estantes para organizar tus elementos de trabajo. Su diseño optimiza el espacio y es compatible con monitores de hasta 19 pulgadas. Disponible también en colores Venezia, Tabaco y Wengue para adaptarse a diferentes estilos de decoración.",
    price: 111764,
    discount: 15,
    category: "Muebles",
    image:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/MKT0369MOS-2.png.jpg-CCynZyX5gI0ViH4kU91VxlFuFGC1T9.jpeg",
    featured: true,
    specifications: {
      Material: "Melamina sobre MDP 15 mm",
      Color: "Blanco",
      "Colores disponibles": "Venezia, Tabaco, Wengue, Blanco",
      "Medidas (Al x An x Prof)": "121 cm x 101 cm x 45 cm",
      Características: "Bandeja deslizable para teclado con correderas metálicas, Repisa con 2 estantes",
      "Compatible con": "Monitor hasta 19 pulgadas",
      Marca: "Mosconi",
      "Peso del paquete": "25 kg",
      "Medidas del paquete": "105x47x14 cm",
    },
    gallery: [
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/MKT0369MOS-2.png.jpg-CCynZyX5gI0ViH4kU91VxlFuFGC1T9.jpeg",
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/MKT0369MOS-1.png.jpg-gp7lJdm4O56y4YfyhBlHKY2uZyvbad.jpeg",
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/MKT0369MOS-3.png.jpg-U2YoiiE7JBPsvuRBk2TJvf5ixVP5SR.jpeg",
    ],
  },
  {
    id: "mueble-organizador-planchado",
    name: "Mueble Organizador De Planchado Mosconi Blanco",
    description:
      "Práctico mueble organizador de planchado con superficie de planchar acolchada color verde. Fabricado en melamina sobre MDP de 15 mm en color blanco, cuenta con 2 puertas con bisagras a resorte y 1 estante interior para almacenar productos de limpieza y planchado. Incluye soporte para plancha y posee ruedas para facilitar su traslado, lo que lo convierte en una solución funcional y móvil para optimizar el espacio en tu hogar.",
    price: 116470,
    discount: 15,
    category: "Muebles",
    image:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/D_NQ_NP_965191-MLA71413428959_082023-O-4LtZEWI6ShZAgjrpdKLZIvhw3uQcKs.webp",
    featured: true,
    specifications: {
      Fabricante: "Mosconi",
      Medidas: "111x36x88 cm",
      Color: "Blanco",
      Material: "Melamina sobre MDP 15 mm",
      Características: "2 puertas con bisagras a resorte y 1 estante",
      Adicionales: "Soporte para plancha, Manijas plásticas color gris, Ruedas para traslado",
    },
    gallery: [
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/D_NQ_NP_965191-MLA71413428959_082023-O-4LtZEWI6ShZAgjrpdKLZIvhw3uQcKs.webp",
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/D_NQ_NP_815133-MLA71369617322_082023-O-otPbKqtiwY7j95p6c2E8UgHL4KfScz.webp",
    ],
  },
  {
    id: "comoda-4-cajones-1-puerta",
    name: "Cómoda 4 Cajones/1 Puerta Express",
    description:
      "Cómoda multifuncional con 4 cajones y 1 puerta, ideal para dormitorios infantiles o juveniles. Fabricada en MDP de 15 mm con terminación UV en color blanco. Los cajones cuentan con correderas plásticas y manijas en colores blanco, rosa y azul que le dan un toque alegre y moderno. La puerta incluye un estante de altura regulable para mayor versatilidad de almacenamiento. Su diseño compacto y funcional optimiza el espacio en cualquier habitación.",
    price: 140000,
    discount: 15,
    category: "Muebles",
    image:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/D_NQ_NP_863850-MLA53141542952_012023-O-62oD7JDNp5Bbm4mvYXOObrlVZkW3mi.webp",
    featured: true,
    specifications: {
      Fabricante: "Mosconi",
      Medidas: "101x48x102 cm",
      Color: "Blanco",
      Material: "MDP 15 mm pintado con terminación UV",
      Cajones: "4 con correderas plásticas",
      "Profundidad del cajón": "42 cm",
      Puerta: "1 con estante de altura regulable",
      Manijas: "Plásticas color blanco, rosa y azul",
    },
    gallery: [
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/D_NQ_NP_863850-MLA53141542952_012023-O-62oD7JDNp5Bbm4mvYXOObrlVZkW3mi.webp",
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/D_NQ_NP_913567-MLA53141542953_012023-O-XwaNalyLVPaNAwrwozJ3wgKe4PaVLy.webp",
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/D_NQ_NP_871584-MLA53141542955_012023-O-Byik4D5qlQesefE3sCIyrRceLXoB65.webp",
    ],
  },
  {
    id: "chifonier-5-cajones-chocolate",
    name: "Chifonier 5 Cajones Pack Color Chocolate",
    description:
      "Chifonier de 5 cajones con diseño funcional y elegante en color chocolate. Fabricado en MDP de 15 mm con revestimiento acrílico UV que garantiza mayor durabilidad y resistencia. Sus 5 cajones con correderas plásticas y manijas color gris plata ofrecen amplio espacio de almacenamiento para ropa y accesorios. Con una carga máxima admisible de 50 kg, este mueble combina practicidad y estética para complementar cualquier dormitorio.",
    price: 76470,
    discount: 15,
    category: "Muebles",
    image:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/D_NQ_NP_724547-MLA82350528671_022025-O-iHydAFsvwLr5tQJiLubV2BNCTPcffg.webp",
    featured: false,
    specifications: {
      "Material Principal": "MDP 15 mm impreso",
      Revestimiento: "Acrílico UV",
      Fondo: "MDF 3 mm",
      Cajones: "5 con peso admisible de 5 kg cada uno",
      Correderas: "Plásticas",
      Manijas: "Plásticas Gris Plata",
      "Carga Máxima Admisible": "50 kg",
      Largo: "91 cm",
      Ancho: "58 cm",
      Profundidad: "38 cm",
      "Colores disponibles": "Chocolate, Caoba, Tissa(Venezia), Mendra, Grei(Nebraska Gris), Blanco, Bambu",
    },
    gallery: [
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/D_NQ_NP_724547-MLA82350528671_022025-O-iHydAFsvwLr5tQJiLubV2BNCTPcffg.webp",
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/D_NQ_NP_770787-MLA82068221932_022025-O-8HqXFcY3OIK0BWW0QRxSDrMROJqMcu.webp",
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/D_NQ_NP_941673-MLA82350413031_022025-O-cYL8RVNydPX25kaIyjD70iB2Vgelg4.webp",
    ],
  },
  {
    id: "placard-6-puertas-2-cajones",
    name: "Ropero Placard 6 Puertas 2 Cajones Dakar Zero Melamina",
    description:
      "Amplio placard de 6 puertas y 2 cajones, perfecto para maximizar el espacio de almacenamiento en tu dormitorio. Fabricado en melamina sobre MDP de 15 mm, disponible en diversos acabados como Carvalho Mezzo frente Blanco, Wengue, Blanco, Tabaco y Venezia. Cuenta con un espacio interior de colgado con barral plástico, 3 estantes fijos y 1 regulable para organizar tu ropa de manera eficiente. Los cajones incluyen correderas metálicas para un deslizamiento suave y mayor durabilidad.",
    price: 258823,
    discount: 15,
    category: "Muebles",
    image:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/D_NQ_NP_888783-MLA49010106997_022022-O-VoP1DHzM7t2bOhH9bByfJ7qrQlt3qc.webp",
    featured: true,
    specifications: {
      Marca: "Mosconi",
      Modelo: "PLACARD 26 DAKAR ZERO",
      Medidas: "169x46x181 cm",
      Material: "Melamina sobre MDP 15 mm",
      Puertas: "6",
      Cajones: "2 con correderas metálicas",
      "Espacio interior": "Barral plástico para colgado, 3 estantes fijos y 1 regulable",
      "Interior y fondo": "Sin pintar",
      Manijas: "Plásticas color gris",
      "Peso máximo por cajón": "5 kg",
      "Medidas interior del cajón": "34x49x11 cm",
      "Colores disponibles": "Carvalho Mezzo frente Blanco, Wengue, Blanco, Tabaco, Venezia",
    },
    gallery: [
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/D_NQ_NP_888783-MLA49010106997_022022-O-VoP1DHzM7t2bOhH9bByfJ7qrQlt3qc.webp",
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/D_NQ_NP_796826-MLA49010106991_022022-O-62fVJL4gAmaLD3Hgfj2JiT28OlJsKi.webp",
    ],
  },
  {
    id: "mueble-apoyo-cocina",
    name: "Mueble Apoyo Cocina Con Ruedas Frutero P/ Microondas",
    description:
      "Mueble multifuncional para cocina con ruedas, ideal para optimizar el espacio en tu hogar. Cuenta con un cajón superior para utensilios, tres bandejas extraíbles plásticas para frutas o verduras, y un compartimento con puerta y estante para almacenamiento adicional. Su superficie superior es perfecta para colocar un microondas u otros electrodomésticos. Las ruedas facilitan su movilidad, permitiéndote ubicarlo donde más lo necesites.",
    price: 85000,
    discount: 0,
    category: "Muebles",
    image: "/products/mueble-cocina-1.png",
    featured: true,
    specifications: {
      Funcionalidad: "Multifunción",
      Características: "Frutero (3 bandejas extraíbles plásticas), Porta microondas, 1 cajón, 1 puerta con estante",
      Movilidad: "Con ruedas",
      Ancho: "0,68 m",
      Alto: "0,91 m",
      Profundidad: "0,40 m",
      Material: "Melamina",
      Color: "Blanco",
    },
    gallery: ["/products/mueble-cocina-1.png", "/products/mueble-cocina-2.png", "/products/mueble-cocina-3.png"],
  },
  {
    id: "barra-desayuno-milano",
    name: "Barra Desayuno Milano 120X44X89 Cm Negro/Roble Dielfe",
    description:
      "La Barra Desayuno Milano de Dielfe es una opción elegante y funcional para su cocina o área de comedor. Con dimensiones de 120x44x89 cm, esta barra está diseñada para ofrecer un espacio cómodo y estilizado para disfrutar de desayunos, comidas rápidas o reuniones informales. El diseño en negro y roble combina la sofisticación del negro con la calidez del roble, creando un contraste atractivo y moderno que se adapta a diversos estilos decorativos. Su diseño compacto y vertical es ideal para espacios más reducidos, maximizando el uso del área disponible sin comprometer la funcionalidad.",
    price: 139000,
    discount: 0,
    category: "Muebles",
    image: "/products/barra-milano-1.jpeg",
    featured: true,
    specifications: {
      "Tipo de Producto": "Desayunadores",
      Color: "Marrón",
      Acabado: "Mate",
      Tono: "Natural-Negro",
      Alto: "89 Cm",
      Ancho: "44,5 Cm",
      Largo: "120 Cm",
      Peso: "12 Kg",
      Extensible: "No",
      Material: "Melamina",
      "Requiere Armado": "Si",
      "Más Información":
        "La barra desayunadora milano tiene un estilo moderno, con líneas simples, dentro de sus características destacamos sus patas metálicas con tubo de sección que no solo le aporta estética, sino que también resistencia, ideal para todo tipo de ambientes.",
      Origen: "Nacional",
      "País de Origen": "Argentina",
      Modelo: "MLD120",
    },
    gallery: ["/products/barra-milano-1.jpeg", "/products/barra-milano-2.jpeg", "/products/barra-milano-3.jpeg"],
  },
  {
    id: "mesa-luz-nordica",
    name: "Mesa De Luz Nórdica Escandinava",
    description:
      "Mesa de luz con diseño nórdico/escandinavo que combina funcionalidad y estética minimalista. Cuenta con un cajón superior y un compartimento inferior con puerta rebatible que proporcionan amplio espacio de almacenamiento para tus objetos personales. Fabricada en madera de pino natural sin tratamiento, esta pieza aporta calidez y un toque contemporáneo a cualquier dormitorio. Sus patas inclinadas le dan un aspecto moderno y distintivo, ideal para espacios con estilo escandinavo.",
    price: 50000,
    discount: 0,
    category: "Muebles",
    image: "/products/mesa-luz-escandinava-1.webp",
    featured: true,
    specifications: {
      Material: "Madera natural",
      Acabado: "Sin lustre",
      Almacenamiento: "1 cajón + puerta rebatible",
      Alto: "60 cm",
      Ancho: "40 cm",
      Profundidad: "30 cm",
      Estilo: "Nórdico/Escandinavo",
    },
    gallery: [
      "/products/mesa-luz-escandinava-1.webp",
      "/products/mesa-luz-escandinava-2.webp",
      "/products/mesa-luz-escandinava-3.webp",
    ],
  },
  {
    id: "modulo-escandinavo",
    name: "Módulo Escandinavo LE075",
    description:
      "El módulo de dos cuerpos de la línea Escandinava, se caracteriza por su estilo minimalista. El diseño está compuesto por un cuerpo principal de melanina y patas de PVC. Este mueble posee seis divisiones internas, dos cerradas con puertas y cuatro libres. Con terminaciones en color blanco combinado con roble bardolino y tiradores de color plateado los cuales acompañan con la estética discreta del diseño. Este módulo se puede adaptar perfectamente al ambiente en el que se lo utilice.",
    price: 99000,
    discount: 0,
    category: "Muebles",
    image: "/products/modulo-escandinavo.png",
    featured: true,
    specifications: {
      "Material del Producto": "Melamina",
      "Cantidad de puertas": "2",
      "Cantidad de estantes": "6",
      "Cantidad de cajones": "0",
      Manijas: "2",
      Medidas: "132*75*30",
      "Requiere armado": "Sí",
      Color: "Blanco con roble",
    },
    gallery: [
      "/products/modulo-escandinavo.png",
      "/products/modulo-escandinavo-2.png",
      "/products/modulo-escandinavo-3.png",
    ],
  },
  {
    id: "silla-escandinava",
    name: "SILLA ESCANDINAVA BOLONIA CAÑO BLANCO TAPIZADO GRIS",
    description:
      "La silla Bolonia combina estilo y confort en un diseño escandinavo elegante y funcional. Su estructura de caño blanco aporta resistencia y estabilidad, mientras que su asiento tapizado en gris brinda comodidad y sofisticación. El respaldo de madera añade un toque cálido y natural, ideal para integrarse en diferentes espacios.",
    price: 55000,
    discount: 0,
    category: "Muebles",
    image: "/products/silla-escandinava.png",
    featured: true,
    specifications: {
      Diseño: "Escandinavo",
      Estructura: "Caño blanco",
      Asiento: "Tapizado en gris",
      Respaldo: "Madera",
      Alto: "84,5 cm",
      Ancho: "43,5 cm",
      Profundidad: "46 cm",
    },
    gallery: ["/products/silla-escandinava.png", "/products/silla-escandinava-2.png"],
  },
  {
    id: "silla-escandinava-negra",
    name: "SILLA ESCANDINAVA BOLONIA CAÑO NEGRO TAPIZADO PLOMO",
    description:
      "La silla Bolonia combina estilo y confort en un diseño escandinavo elegante y funcional. Su estructura de caño negro aporta resistencia y estabilidad, mientras que su asiento tapizado en gris plomo brinda comodidad y sofisticación. El respaldo de madera añade un toque cálido y natural, ideal para integrarse en diferentes espacios.",
    price: 55000,
    discount: 0,
    category: "Muebles",
    image: "/products/silla-bolonia-negra-1.png",
    featured: false,
    specifications: {
      Diseño: "Escandinavo, moderno y versátil",
      Estructura: "Caño negro, resistente y duradera",
      Asiento: "Tapizado en gris plomo, cómodo y fácil de combinar",
      Respaldo: "Madera, aportando un toque natural",
      "Uso recomendado": "Comedores, livings, oficinas o espacios de reunión",
      Alto: "84,5 cm",
      Ancho: "43,5 cm",
      Profundidad: "46 cm",
    },
    gallery: ["/products/silla-bolonia-negra-1.png", "/products/silla-bolonia-negra-2.png"],
  },
  {
    id: "mesa-puket",
    name: "Mesa Puket Auxiliar",
    description:
      "Mesa de diseño redondeado modelo Puket, pensada para ser utilizada al exterior, fabricada con material resistente y duradero. Disponible en color blanco y gris. Todos nuestros productos plásticos son fáciles de limpiar, resistentes a los rayos UV y están elaborados para que no dañen el ambiente.",
    price: 17000,
    discount: 0,
    category: "Muebles",
    image: "/products/mesa-puket-blanca.jpeg",
    featured: false,
    specifications: {
      Material: "Plástico resistente",
      Uso: "Interior y exterior",
      "Resistente a rayos UV": "Sí",
      "Fácil limpieza": "Sí",
      "Colores disponibles": "Blanco, Gris",
      Diseño: "Redondeado",
    },
    gallery: ["/products/mesa-puket-blanca.jpeg", "/products/mesa-puket-gris.webp"],
  },
  {
    id: "mesa-luz-1-puerta-1-cajon",
    name: "Mesa de Luz 1 Puerta 1 Cajón",
    description:
      "Mesa de luz funcional y moderna con un cajón y una puerta, ideal para el dormitorio. Fabricada en MDP de 15 mm impreso con revestimiento acrílico UV que garantiza durabilidad y resistencia. Disponible en colores blanco y chocolate, se adapta perfectamente a cualquier estilo de decoración. Sus medidas compactas (56 cm de alto, 38 cm de ancho y 37 cm de profundidad) la hacen perfecta para espacios reducidos.",
    price: 41175,
    discount: 15,
    category: "Muebles",
    image: "/products/mesa-luz-chocolate.jpeg",
    featured: true,
    specifications: {
      "Material principal": "MDP 15 mm impreso",
      Fondo: "MDF 3 mm",
      Revestimiento: "Acrílico UV",
      Cajones: "1",
      Manijas: "Plástico (Gris Plata)",
      "Correderas de cajones": "Plásticas",
      "Carga admisible total": "15 kg",
      Alto: "0,56 m",
      Ancho: "0,38 m",
      Profundidad: "0,37 m",
      "Colores disponibles": "Blanco, Chocolate",
    },
    gallery: [
      "/products/mesa-luz-chocolate.jpeg",
      "/products/mesa-luz-blanca.jpeg",
      "/products/mesa-luz-chocolate-abierta.jpeg",
      "/products/mesa-luz-blanca-abierta.jpeg",
      "/products/mesa-luz-blanca-ambiente.jpeg",
    ],
  },
  {
    id: "placard-2-puertas-2-cajones",
    name: "Placard 2 Puertas 2 Cajones",
    description:
      "Placard funcional y espacioso con dos puertas y dos cajones, perfecto para organizar tu ropa y accesorios. Fabricado en melamina de 15 mm que garantiza durabilidad y resistencia. Disponible en colores caoba, chocolate y blanco para adaptarse a cualquier estilo de decoración. Sus dimensiones (1,81 m de alto, 0,57 m de ancho y 0,46 m de profundidad) ofrecen amplio espacio de almacenamiento sin ocupar demasiado espacio en la habitación.",
    price: 77767,
    discount: 10,
    category: "Muebles",
    image: "/products/placard-caoba.jpeg",
    featured: true,
    specifications: {
      Material: "Melamina de 15 mm",
      Puertas: "2",
      Cajones: "2 con guías",
      Manijas: "Plástico",
      Barral: "Plástico",
      "Acabado interior": "Mate, no revestido",
      Ancho: "0,57 m",
      Alto: "1,81 m",
      Profundidad: "0,46 m",
      Peso: "40 kg",
      "Colores disponibles": "Caoba, Chocolate, Blanco",
    },
    gallery: [
      "/products/placard-caoba.jpeg",
      "/products/placard-chocolate.jpeg",
      "/products/placard-blanco.jpeg",
      "/products/placard-caoba-abierto.jpeg",
      "/products/dormitorio-caoba.jpeg",
    ],
  },
]

